[workspace]
members = [
  "utils",
  "apps/cross/liner/desktop",
  "apps/cross/liner/core",
  "apps/cross/liner/tui",
  "apps/cross/liner/core-wasm",
  "apps/deepl/*",
  "service/apps-service/api/database",
  "service/apps-service/api/graphql",
]
resolver = "2"
