#ifndef INFRA_CORE
#define INFRA_CORE
#include "fmt/chrono.h"
#include "fmt/color.h"
#include "fmt/core.h"
#include "fmt/ranges.h"
#include "range/v3/all.hpp"
#include <algorithm>
#include <array>
#include <atomic>
#include <concepts>
#include <deque>
#include <exception>
#include <filesystem>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <variant>
#include <vector>
#include <complex>
#include <compare>
#include <any>
#include <chrono>
#include <typeinfo>
#include <type_traits>
#include <typeindex>
#include <concepts>
#include <atomic>
#include <mutex>
#include <bitset>
#include <bit>
#include <future>
#include <exception>
#include "glog/logging.h"
#endif
