[package]
name = "infra_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-futures = "0.2"
tracing-appender = "0.2"
futures-util = "0.3"

