CREATE TABLE IF NOT EXISTS TODO (
    ID UUID PRIMARY KEY,
    index SERIAL NOT NULL,
    content TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    overdue_time TIMESTAMP WITH TIME ZONE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE
);

